### ISSUE TITLE
Продемонстрировать кастомизацию компонент

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.3#1]
Сейчас на самодельных страницах продемонстрировано использование компонент, которые ты сделал в UI Kit'e, но помимо этого, тебе нужно продемонстрировать саму _кастомизацию_ компонент, т.е. чтобы они имели цвета, отличные от тех, что есть в UI Kit'e, форму и т.п.

**Comment by chmnkh** [comment]
Так она вроде есть)
Например: 

- модификатор color_grey для кнопки поиска в шапке; 
- страница Event, модификатор added (убирает кнопку add to calendar) для event в My Events; 
- страница Articles, модификатор multiple для второго dropdown в Filter;
- страница New event,  у карты в Choose a place скрыт адрес после названия карты.

**Comment by Zarwlar** [comment]
Этого мало) Поиграйся ещё с цветами и формами)

**Comment by chmnkh** [comment]
Добавил:
- синий цвет для news-article-preview (страница News);
- другую форму для arrow-button (страница News);
- красный цвет для toggle над картой (страница Events);
- более угловатую форму для toggle над картой (страница Events);
- более угловатую форму для tick-box (страница New Event, там, где Event Options).
Так норм? А то продолжать можно довольно долго, но суть вроде бы одна и та же)

**Comment by Geksanit** [comment]
А ещё нужно продемонстрировать кастомизацию профилей, новостей и ивентов (текст, картинки).

**Comment by chmnkh** [comment]
@Geksanit  добавил.

**Comment by Geksanit** [comment]
Закрывай ишьюс.
