### ISSUE TITLE
Обращаться к DOM через this._$block

### ISSUE THREAD

**Issue by Znack** [AlexeyCheremnykh/task-2.3#2]
Если уже имеется инициализированный атрибут `this._$calendar = $(elem);`, то потом везде через него надо обращаться, чтобы лишний раз jquery не инициализировать и чтобы можно было легко вырезать код и вставлять в другие места. `this._$day = $(elem).children('.js-calendar__day');` — я не могу потом сразу перенести, атк как elem не будет в замыкании, например. НУ и это неединообразие, так как в конструкторе через $(elem) идет обращение, а в остальных методах будет через this._$calendar

И рекомендация элементы корневые прямо называть this._$block, а не конкретным названием, так как легче потом код можно копипастить, если надо будет, или переименовывать. Из контекста класса понятно, что там календарь :)

**Comment by chmnkh** [comment]
Исправил
