### ISSUE TITLE
Избегать дублирования кода

### ISSUE THREAD

**Issue by Znack** [AlexeyCheremnykh/task-2.3#3]
Вот хороший пример, когда надо было вложенный тернарник использовать, чтобы добавить один класс .categories-navigation__category_selected, и можно было бы не дублировать :)
https://github.com/AlexeyCheremnykh/task-2.3/blob/refactoring/src/blocks/categories-navigation/categories-navigation.pug

**Comment by chmnkh** [comment]
Исправил
