### ISSUE TITLE
А зачем замыкание currentDate в calendar.js

### ISSUE THREAD

**Issue by Znack** [AlexeyCheremnykh/task-2.3#4]
Я так понял, там можно было бы и не в замыкании прееменную хранить :)

**Comment by chmnkh** [comment]
Не совсем понял именно про замыкание, мне ж там помимо использования этой даты в onSelect (старая 18 строчка), нужно было еще и в initElement (23 строчка) её использовать, отсюда для onSelecta она и достается из замыкания.
В любом случае, я сделал через свойство класса, мне кажется, так лучше)

**Comment by Znack** [comment]
Я все равно не понимаю, зачем для этого должна быть общая переменная :) У тебя если это будут две переменные с двумя разными именами — все равно все должно работать (ну по крайней мере при старом коде).

А в целом вынести в свойство объекта я согласен, хотя это и не нужно сейчас, это логично хранить текущее выбранное время :)
